language: ruby
bundler_args: --without development --path vendor/bundle
rvm:
  - 2.3.0
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - DB=mysql
